sudo: false
language: node_js
install:
- npm install
- npm install -g grunt-cli
script: DEPLOYMENT_TRACKER_MOCK_REDIS=true grunt
deploy:
  provider: npm
  email: mcp_infrastructure@cimpress.com
  api_key:
    secure: dp3S2ZulHCP2fjd6sl6Rqn6XGk/Rvhk+wALOfi250/vwtidMh8nS52MCrdflz+BbtHkOvxookbK+sp/rcfiJCCiijuXqTQ/apye7NFfAPCNszAOqGTnjvZoScx/rZECK74yM70ioCn9HPTyovN8/PMxdy7i6M/ILAEBN2ghBdBtc9w5ixdb8+2kH7VBP2tHIB1+zUReoDII+uSR2a5iptHU1cteZIjn3mn7H4M6xXfNYWdvAhFmD5Tw/OFFVQCC/u/mBAxQx+GyQG3u97kke2oafKTcESxGgvjpV/vSRnAKoO+GfbVJFQ4kh+wSc7x5aktCF41w5MGy2jZ6RsuBQJVwHAZZZVT6S+UfLZtl9PjPK3R1iAgOzPgPXgJYIErTYdut5xXCgW1pK1uGCW17U8678W2AvdOpBkCAzFHGovGDfcEeewKsMWh15NXqfvBu9l6BsRAQaHrif/8jjT0jXbdKsOBpgMaCO1Qch1MVcC0HkF5lWkJ1IiYk/WTBHo9xUsLEpXYInWrs07hMUqJ4v9KTdJiSy3NPmsRYNnfiMZAntVRZZunDsCEk923WvTlno8mE/hhrUhRGB3fjW3edpTulc2pT6x0BdXRcE5u5bB1xQxvbJka2IRC3DcYNGPJacWLUwdVluBXo6K85+fPA1Dr81L9Sf/Eb2AV3Cdyv5SRM=
  on:
    tags: true
    all_branches: true
