sudo: false
language: node_js
install:
- npm install
- npm install -g grunt-cli
script: DEPLOYMENT_TRACKER_MOCK_REDIS=true grunt
deploy:
  provider: npm
  email: mcp_infrastructure@cimpress.com
  api_key:
    secure: JLF2V1/afT0+QAtOQx/fcqVuL7MhXI3UX7gab/4HRfT88UUkGTvQyKsK97vErQHPKrox+1VQmU9ad9g7QmyLXhn7c+kqHR60eB/tVLXmcBPmROHN4qNPpEwGO1bXhaTPvdUV2xXPvpooqui06YOjsNJ95Zyth5QKi3UKmCXhLObg50q/RmkUhSLaZsFWplgUmp5NJEg4OnaojRGc4iVV9XTKJUhQnSxTnSm00nphyE0n98TFgx7OJmwDFsIz+tHlBBwPtTM0470PYIg4pimmGXhFscMAkYP26hsMDPGUwjc30rCxSXAja3yb/BG3xmlhw9IDBHOmTDZzbrbhufEFZN1uXpQwB52pykPX8i7poTOmTMMgLydq3PAkoX5/XHMS5T7G/wq6Vaodldoq1DxkNddaCvyND6hPzSCbza9F15GC4q0a6laK4Zbl6RgZAstr84ajEyFuKScfo4h4orR9TFIx3MISB5MCICmqd6SN+fctPEjnXWWz53kvED093NjgWkwgYobTBolgwJBQr4Fm7R74mZTCVVxFkGcDWS/prKQqTkBbVjNXBE+xxcQMpADdIPAwv9srxYC2e0Mw/3aiG56ZSdRej3vxBvn5Z5NisfStL3X0z1t29xvpaE7wvfZueUyq3V21TvxyAtOVOAFoOr/hqda1rGPZJOPSEeH5kBk=
  on:
    tags: true
    all_branches: true
