sudo: false
language: node_js
install:
- npm install
- npm install -g grunt-cli
script: DEPLOYMENT_TRACKER_MOCK_REDIS=true grunt
deploy:
  provider: npm
  email: mcp_infrastructure@cimpress.com
  api_key:
    secure: OA4nJBObpp1xe6o+bIY5XjMs+wagW89aVlM0Z1FbRa/QCkQjYknYSNSNMZWtknM+31ZUd/HqWbUUbp2DisuX35x4lM6vlIpC9QJyrVhMGDncvpnuBMUk6DcyoC5Auhg8ow7JkqAPhL4y6gOHwgw4lsLt7v6elI3y1MT3i9wUD4FNlPYhiyOdK1ikeDJ1nui9+SgXy4fxWKYEoKgRgGXrAn4f1+132qUXHG8ICatpXDJJFB4ZirMZJCCY+ey6qQvdEhcW0vmeYt0U83RLAUOO3i/Aj1EJDiCW+nGbqgjAr1d5tL3cH38SwGO/pPcv8bLdEU6bMwfECffJozxWcFrN2vRAsClDPcEDWM4eslIlhWarrDeAEGFRxl5WH/0v7h5p3kLmF7z4Hca5k0wa54LugSdWHB6CZu6M8wU4gxzxqWBnqCmRT2E/i8IPOwG1UlT+IhPkqaDYpVmGZkSpPZODle6DMglsqh1HsdTbYzkeS4q+ELeOtvPEhsH1YwnB47ES1c67PDg2jiUclqOvOuUQ/qbgslDWv5Chl3VeYX1fGfRQiRBG9awrNqzsPfgx9viuY/UmXB+zWcV6zuK2cQs3gCj6j/m8fdOylDYxXd7gWFnWHPzufHq/inG+y6anHOODU6de8UvPgSLl3y194XQZW1j096RRbtOUbJwJoNG1IFc=
  on:
    tags: true
    all_branches: true
